# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda create --yes --quiet --name pp_env
  displayName: Create Anaconda environment

- bash: |
    source activate pp_env
    conda install --yes --quiet --name pp_env pip numpy mkl scipy python-dateutil pandas scikit-learn dendropy sharedmem numba matplotlib networkx mash hdbscan rapidnj
  displayName: Install Anaconda packages

- script: |
    source activate pp_env
    python -m pip install --no-deps --ignore-installed .
    cd test && python run_test.py
  displayName: 'Install and run_test.py'
