name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pip
  - numpy
  - mkl
  - scipy
  - python-dateutil
  - pandas
  - scikit-learn
  - dendropy
  - matplotlib
  - networkx
  - mash
  - hdbscan
  - rapidnj
  - h5py
  - pp-sketchlib >=1.5.1
  - graph-tool
