name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pip
  - numpy
  - scipy
  - python-dateutil
  - pandas
  - scikit-learn
  - dendropy
  - matplotlib-base
  - hdbscan
  - rapidnj
  - h5py
  - pp-sketchlib >=1.6.0
  - graph-tool
  - requests
  - flask
  - flask-cors
  - gunicorn
  - networkx
  - xorg-libxi
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxpm
  - xorg-libxaw
  - xorg-libxfixes
