name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pip
  - numpy
  - scipy
  - python-dateutil
  - pandas
  - scikit-learn
  - dendropy >=4.4.0
  - matplotlib
  - mash
  - hdbscan
  - rapidnj
  - h5py
  - pp-sketchlib >=1.6.0
  - graph-tool
  - requests
  - flask
  - flask-cors
  - networkx
