name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pip
  - numpy
  - scipy
  - python-dateutil
  - pandas
  - scikit-learn >=0.24
  - matplotlib-base
  - dendropy >=4.4.0
  - treeswift
  - matplotlib
  - hdbscan
  - rapidnj
  - h5py ==3.6.0
  - pp-sketchlib >=2.0.0
  - graph-tool >=2.35
  - networkx
  - xorg-libxi
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxpm
  - xorg-libxaw
  - xorg-libxfixes
  - pybind11
  - eigen
  - openblas
  - cmake >= 3.18
  - libgfortran-ng
  - boost-cpp
  - libgomp
  - tqdm
