name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pip
  - numpy
  - scipy
  - python-dateutil
  - pandas
  - scikit-learn
  - matplotlib-base
  - dendropy >=4.4.0
  - matplotlib
  - hdbscan
  - rapidnj
  - h5py
  - pp-sketchlib >=1.6.2
  - graph-tool
  - requests
  - flask
  - flask-cors
  - gunicorn
  - networkx
  - xorg-libxi
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxpm
  - xorg-libxaw
  - xorg-libxfixes
  - pybind11
  - eigen
  - openblas
  - cmake >= 3.18
  - libgfortran-ng
  - boost-cpp
  - libgomp
  - tqdm
  - apscheduler
