name: Build and push Docker image

on:
  push:
    branches:
      - master
      - docker

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . --file docker/Dockerfile -t poppunk/poppunk_api:${{ github.sha }}
        docker push poppunk/poppunk_api:${{ github.sha }}